name: Main Edge Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Build Code
        run: yarn build

      - name: Create args file
        # "create the arguments at runtime because of the secrets"
        run: |
          cat > ./args.json << EOF
            {}
          EOF

      - name: edge-computing-actions
        id: azion_edge
        uses: jcbsfilho/edge-computing-deploy@v3.1.0
        with:
          azionPersonalToken: ${{ secrets.AZION_PERSONAL_TOKEN }}
          commitConfig: true
          functionFilePath: ".edge/worker.js"
          functionArgsFilePath: "args.json"
          configFilePath: "azion/azion.json"

      - name: Get the output Azion Edge Deploy
        run: |
          echo "Application ID-= ${{ steps.azion_edge.outputs.applicationId }}"
